// Generated by LiveScript 1.3.1
(function(){
  var readline, Sequelize, sequelize;
  readline = require('readline');
  Sequelize = require('sequelize');
  sequelize = new Sequelize('database_name', 'username', 'password', {
    dialect: 'postgres',
    port: 5432
  });
  readline = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false
  });
  readline.on('line', function(line){
    var temp, mid, retweeted_status_mid, uid, retweeted_uid, source, image, text, geo, created_at, deleted_last_seen, permission_denied;
    temp = line.split(',');
    mid = temp[0], retweeted_status_mid = temp[1], uid = temp[2], retweeted_uid = temp[3], source = temp[4], image = temp[5], text = temp[6], geo = temp[7], created_at = temp[8], deleted_last_seen = temp[9], permission_denied = temp[10];
  });
}).call(this);
