// Generated by LiveScript 1.3.1
(function(){
  var cluster, func;
  cluster = require('cluster');
  func = function(){
    console.log(cluster.worker.process.pid);
    setTimeout(function(){
      func();
    }, 1000);
  };
  func();
}).call(this);
