// Generated by LiveScript 1.3.1
(function(){
  var readline, Sequelize, $config, sequelize, Tweets;
  readline = require('readline');
  Sequelize = require('sequelize');
  $config = require('../config.json');
  sequelize = new Sequelize($config.database, $config.username, $config.password, {
    host: $config.host,
    dialect: $config.dialect,
    port: $config.port
  });
  Tweets = sequelize.define('Tweets', {
    mid: {
      type: Sequelize.STRING,
      primaryKey: true
    },
    retweeted_status_mid: {
      type: Sequelize.STRING
    },
    uid: {
      type: Sequelize.STRING
    },
    retweeted_uid: {
      type: Sequelize.STRING
    },
    source: {
      type: Sequelize.STRING
    },
    image: {
      type: Sequelize.BOOLEAN
    },
    text: {
      type: Sequelize.TEXT
    },
    geo: {
      type: Sequelize.JSON
    },
    created_at: {
      type: Sequelize.DATE
    },
    deleted_last_seen: {
      type: Sequelize.DATE
    },
    permission_denied: {
      type: Sequelize.INTEGER
    }
  });
  Tweets.sequelize.sync().success(function(){
    var readline;
    console.log('123');
    readline = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
      terminal: false
    });
    readline.on('line', function(line){
      var temp, mid, retweeted_status_mid, uid, retweeted_uid, source, image, text, geo, created_at, deleted_last_seen, permission_denied;
      temp = line.split(',');
      mid = temp[0], retweeted_status_mid = temp[1], uid = temp[2], retweeted_uid = temp[3], source = temp[4], image = temp[5], text = temp[6], geo = temp[7], created_at = temp[8], deleted_last_seen = temp[9], permission_denied = temp[10];
      console.log(temp);
    });
  });
}).call(this);
